name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4]
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
    - uses: actions/checkout@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Check PHP and composer version
      run: php -v && composer --version

    - name: Install dependencies
      run: composer u --${{ matrix.dependency-version }} --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
