name: Tests (Pest)

#on: [push]

on:
  push:
    branches:
      - main
  #      - develop
  #      - '*.x'
  pull_request:
#  schedule:
#    - cron: '0 0 * * 5'

#permissions:
#  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.2, 8.1]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          #          coverage: pcov
          coverage: none

      - name: Install Composer dependencies
        run: composer i --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/pest --ci --parallel #--coverage-clover coverage.xml

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}